[options]
addons_path = odoo/addons,custom_addons
db_host = localhost
db_port = 5432
db_user = odoo19
db_password = admin
admin_passwd = $pbkdf2-sha512$600000$YsxZC0FoDYGQsvZ.T2ktxQ$Q0ds/1NarUWK8bquvqDNy42Sq9BRl/2eM32IfnkrgKYoaqhHbYmF.kKAYp.b3l935PxUqMHYFuMYjlHxtK0bZw
http_interface = 127.0.0.1

