{
    "name": "ICS Core",
    "version": "19.0.1.0.0",
    "summary": "ICS foundational module for contacts, CRM, product taxonomy, and security",
    "category": "Customizations",
    "author": "ICS / GMS",
    "license": "LGPL-3",
    "depends": [
        "base",
        "contacts",
        "crm",
        "sale",
        
        "product",
        "mail",
        "account",
    ],
    "data": [
    "security/ics_security.xml",
    "security/ics_record_rules.xml",
    "security/ir.model.access.csv",
    "data/product_category_data.xml",
    "data/accounting_baseline_data.xml",
    "views/res_partner_views.xml",
    "views/crm_lead_views.xml",
    "views/product_category_views.xml",
    "views/product_template_views.xml",
],
    "installable": True,
    "application": False,
    "auto_install": False,
}