{
    "name": "ICS Core",
    "version": "19.0.1.0.0",
    "summary": "ICS foundational module for contacts, CRM, product taxonomy, and security",
    "category": "Customizations",
    "author": "ICS / GMS",
    "license": "LGPL-3",
    "depends": [
        "base",
        "contacts",
        "crm",
        "sale",
        "sale_subscription",
        "product",
        "mail",
        "account",
    ],
    "data": [
        "security/ics_security.xml",
        "security/ir.model.access.csv",
        "views/res_partner_views.xml",
        "views/crm_lead_views.xml",
        "views/product_category_views.xml",
        "views/product_template_views.xml",
        "data/product_category_data.xml",
    ],
    "installable": True,
    "application": False,
    "auto_install": False,
}