from . import res_partner
from . import crm_lead
from . import product_product
from . import product_template
from . import client_proposal
from . import client_proposal_line
from . import client_proposal_merchant
from . import proposal_merchant
from . import proposal_line
from . import proposal_rate_table
from . import sow_template
from . import proposal_section
from . import proposal_ack_item
from . import proposal_review
from . import proposal_acceptance
from . import customer_account
from . import merchant_account
from . import supplier_service
from . import forecast_record
from . import commission_line
from . import commission_earning
from . import payout_batch
from . import payout_line
from . import recipient_statement
from . import recipient_statement_line

